---

- name: Install Load Balancer
  become: true
  tags: install
  block:

    - name: Install needed packages
      dnf:
        name: "{{ packages_lb }}"
        state: latest

    - name: setup firewall ports
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
        zone: public
      with_items: "{{ ports_lb }}"

    - name: Write out haproxy config file
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        owner: haproxy
        group: haproxy

    - name: SELinux role to allow HAProxy to access ports 6443 and 22623
      include_role:
        name: rhel-system-roles.selinux

    - name: Starting HAProxy service
      service:
        name: "{{ item }}"
        enabled: yes
        state: restarted
      with_items:
        - haproxy


- name: Remove Load Balancer
  become: true
  tags: remove
  block:

    - name: Configure Firewalld
      ignore_errors: yes
      firewalld:
        zone: public
        state: disabled
        permanent: yes
        port: "{{ item }}"
        immediate: yes
      with_items: "{{ ports_lb }}"

    - name: Remove packages
      dnf:
        name: "{{ packages_lb }}"
        state: removed
