---
srv_interface: "enp7s0"
srv_ip: "172.16.0.7"
nodes_subnet24: "172.16.0"
baseName: "lab"
baseDomain: "local"

nodes:
  bootstrap:
    - name: "bootstrap"
      ipaddr: "{{ nodes_subnet24 | default ('192.168.126')}}.10"
      netmask: "255.255.255.0"
      gw: "{{ nodes_subnet24 | default ('192.168.126')}}.254"
      macaddr: "52:54:00:d8:6f:16"
      disk: "vda"
      boot: "bios"
      nic_pxe: enp1s0
  masters:
    - name: "master1"
      ipaddr: "{{ nodes_subnet24 | default ('192.168.126')}}.11"
      netmask: "255.255.255.0"
      gw: "{{ nodes_subnet24 | default ('192.168.126')}}.254"
      macaddr: "0c:c4:7a:20:60:c8"
      disk: "sda"
      boot: "bios"
      nic_pxe: ens1f0
    - name: "master2"
      ipaddr: "{{ nodes_subnet24 | default ('192.168.126')}}.12"
      netmask: "255.255.255.0"
      gw: "{{ nodes_subnet24 | default ('192.168.126')}}.254"
      macaddr: "0c:c4:7a:20:61:c8"
      disk: "sda"
      boot: "bios"
      nic_pxe: ens1f0
    - name: "master3"
      ipaddr: "{{ nodes_subnet24 | default ('192.168.126')}}.13"
      netmask: "255.255.255.0"
      gw: "{{ nodes_subnet24 | default ('192.168.126')}}.254"
      macaddr: "3c:fd:fe:9e:7e:21"
      disk: "sda"
      boot: "uefi"
      nic_pxe: ens803f1
  workers:
    - name: "worker1"
      ipaddr: "{{ nodes_subnet24 | default ('192.168.126')}}.21"
      netmask: "255.255.255.0"
      gw: "{{ nodes_subnet24 | default ('192.168.126')}}.254"
      macaddr: "3c:fd:fe:9e:7b:a9"
      disk: "sda"
      boot: "uefi"
      nic_pxe: ens803f1
    - name: "worker2"
      ipaddr: "{{ nodes_subnet24 | default ('192.168.126')}}.22"
      netmask: "255.255.255.0"
      gw: "{{ nodes_subnet24 | default ('192.168.126')}}.254"
      macaddr: "3c:fd:fe:aa:46:60"
      disk: "sda"
      boot: "uefi"
      nic_pxe: ens802f0
    - name: "worker3"
      ipaddr: "{{ nodes_subnet24 | default ('192.168.126')}}.23"
      netmask: "255.255.255.0"
      gw: "{{ nodes_subnet24 | default ('192.168.126')}}.254"
      macaddr: "3c:fd:fe:ab:b0:38"
      disk: "nvme0n1"
      boot: "uefi"
      nic_pxe: ens786f0
    - name: "worker4"
      ipaddr: "{{ nodes_subnet24 | default ('192.168.126')}}.24"
      netmask: "255.255.255.0"
      gw: "{{ nodes_subnet24 | default ('192.168.126')}}.254"
      macaddr: "3c:fd:fe:ab:a6:81"
      disk: "nvme0n1"
      boot: "uefi"
      nic_pxe: ens786f1
    - name: "worker5"
      ipaddr: "{{ nodes_subnet24 | default ('192.168.126')}}.25"
      netmask: "255.255.255.0"
      gw: "{{ nodes_subnet24 | default ('192.168.126')}}.254"
      macaddr: "3c:fd:fe:ab:b3:71"
      disk: "nvme0n1"
      boot: "uefi"
      nic_pxe: ens786f1

dhcp:
  gateway: "{{ nodes_subnet24 | default ('192.168.126')}}.254"
  broadcast: "{{ nodes_subnet24 | default ('192.168.126')}}.255"
  netmask: "255.255.255.0"
  poolstart: "{{ nodes_subnet24 | default ('192.168.126')}}.128"
  poolend: "{{ nodes_subnet24 | default ('192.168.126')}}.252"
  subnet: "{{ nodes_subnet24 | default ('192.168.126')}}.0"

ocp_mirror: "https://mirror.openshift.com/pub/openshift-v4"

ocp_metal: "{{ ocp_mirror }}/dependencies/rhcos/4.{{ ocp_release.split('.')[1] | lower }}/latest/rhcos-{{ ocp_release }}-x86_64-metal.x86_64.raw.gz"
ocp_initramfs: "{{ ocp_mirror }}/dependencies/rhcos/4.{{ ocp_release.split('.')[1] | lower }}/latest/rhcos-{{ ocp_release }}-x86_64-installer-initramfs.x86_64.img"
ocp_kernel: "{{ ocp_mirror }}/dependencies/rhcos/4.{{ ocp_release.split('.')[1] | lower }}/latest/rhcos-{{ ocp_release }}-x86_64-installer-kernel-x86_64"

ign_folder: /var/www/html/ignition
ocp_install_path: "/root/ocp"

ocp_folders:
  - "{{ ign_folder }}"
  - "{{ ocp_install_path }}"
  - "{{ folders_pxe }}"
  - /root/bin

ocp_release: "4.5.2"

#https://unix.stackexchange.com/questions/363878/which-selinux-policies-apply-to-haproxy
selinux_policy: targeted
selinux_state: enforcing
selinux_ports:
  - { ports: '6443', proto: 'tcp', setype: 'http_port_t', state: 'present' }
  - { ports: '22623', proto: 'tcp', setype: 'http_port_t', state: 'present' }
  - { ports: '9000', proto: 'tcp', setype: 'http_port_t', state: 'present' }
  - { ports: '8080', proto: 'tcp', setype: 'http_port_t', state: 'present' }
  
#check results via semanage port -l | grep -E 'http_cache_port_t|commplex_main_port_t|http_port_t'

mount_point: /tmp/iso
efi_dir: "{{ mount_point }}/EFI/BOOT"
bios_dir: /usr/share/syslinux
boot_dir: "{{ mount_point }}/images/pxeboot"
boot_iso: rhel-8.2-x86_64-boot.iso
rhel_version: RHEL-8.2

efifiles:
  - BOOTX64.EFI
  - grubx64.efi
biosfiles:
  - pxelinux.0
  - ldlinux.c32
bootfiles:
  - initrd.img
  - vmlinuz
tftp_dir: /var/lib/tftpboot
folders_pxe:
  - "{{ tftp_dir }}/uefi"
  - "{{ tftp_dir }}/images"
  - "{{ tftp_dir }}/images/{{ rhel_version }}"
  - "{{ tftp_dir }}/pxelinux"
  - "{{ tftp_dir }}/pxelinux/pxelinux.cfg"
  - /var/www/html/images
  - /var/www/html/kickstarts
  - "/var/www/html/{{ rhel_version }}"