---
# vars file for ocp-prereq-role
packages_lb:
  - haproxy
  - policycoreutils-python-utils
  - setools-console
ports_lb:
  - 80/tcp
  - 443/tcp
  - 6443/tcp
  - 22623/tcp
  - 9000/tcp
#https://unix.stackexchange.com/questions/363878/which-selinux-policies-apply-to-haproxy
selinux_policy: targeted
selinux_state: enforcing
selinux_ports:
  - { ports: '6443', proto: 'tcp', setype: 'http_port_t', state: 'present' }
  - { ports: '22623', proto: 'tcp', setype: 'http_port_t', state: 'present' }
  - { ports: '9000', proto: 'tcp', setype: 'http_port_t', state: 'present' }
#check results via semanage port -l | grep -E 'http_cache_port_t|commplex_main_port_t|http_port_t'

mount_point: /tmp/iso
efi_dir: "{{ mount_point }}/EFI/BOOT/"
boot_dir: "{{ mount_point }}/images/pxeboot/"
services_pxe:
  - tftp
packages_pxe:
  - tftp-server
  - dhcp-server
  - xinetd
efifiles:
  - BOOTX64.EFI
  - grubx64.efi
bootfiles:
  - initrd.img
  - vmlinuz
tftp_dir: /var/lib/tftpboot
folders_pxe:
  - "{{ tftp_dir }}/uefi"
  - "{{ tftp_dir }}/images/{{ rhel_version }}"
  - /var/www/html/kickstarts
  - "/var/www/html/{{ rhel_version }}"
systemd_services_pxe:
  - tftp.service
  - xinetd.service
boot_iso: rhel-8.2-x86_64-boot.iso
rhel_version: RHEL-8.2