---
# tasks file for createVMs
- name: Install virt-install
  dnf:
    name: virt-install
    state: latest

- name: Setup OCP bootstrap VM
  command: "virt-install
    --name {{ nodes.bootstrap.name }}
    --disk size=50
    --ram 16000
    --cpu host
    --vcpus 8
    --os-type linux
    --os-variant rhel8.2
    --network network=ServicesTrunk,mac=52:54:60:11:11:11
    --pxe
    --noautoconsole