---
# tasks file for createVMs
- name: Install virt-install
  dnf:
    name: virt-install
    state: latest

- name: Setup OCP bootstrap VM
  command: "virt-install
    --name {{ nodes.bootstrap.name }}
    --disk size=50
    --ram 16000
    --cpu host
    --vcpus 8
    --os-type linux
    --os-variant rhel8.2
    --network network=VLAN501MGMT
    --network network=ServicesTrunk,mac=52:54:60:11:11:11
    --noautoconsole
    --location http://{{ srv_ip }}:8080/images/
    --extra-args 'nomodeset rd.neednet=1 coreos.inst=yes coreos.inst.install_dev=vda coreos.inst.image_url=http://{{ srv_ip }}:8080/images/rhcos-metal.raw.gz coreos.inst.ignition_url=http://{{ srv_ip }}:8080/ignition/bootstrap.ign'"

