---
- include_vars: "vault"
- name: Powering on or rebooting the server for PXE
  hpilo_boot:
    host: "{{ item }}"
    login: "{{ vault_ipmiuser }}"
    password: "{{ vault_ipmipass }}"
    force: yes
    media: network
  delegate_to: localhost
  with_items:
    - 192.168.16.138
    - 192.168.16.133

- name: Set servers to boot from network on net boot
  ipmi_boot:
    name: "{{ item }}"
    user: "{{ vault_ipmiuser }}"
    password: "{{ vault_ipmipass }}"
    bootdev: network
    uefiboot: yes
  with_items:
    - 192.168.16.129
    - 192.168.16.130
    - 192.168.16.131
    - 192.168.16.132
    - 192.168.16.136
    - 192.168.16.137

- name: Set servers to power on
  ipmi_power:
    name: "{{ item }}"
    user: "{{ vault_ipmiuser }}"
    password: "{{ vault_ipmipass }}"
    state: boot
  with_items:
    - 192.168.16.129
    - 192.168.16.130
    - 192.168.16.131
    - 192.168.16.132
    - 192.168.16.136
    - 192.168.16.137
