---
# tasks file for ocp-prereq-role
- include_vars: "vault"

  tags: [ install, remove ]
  when: ocp_install_config_path != ""

- include_tasks: "ocp-secret.yml"
  when: ocp_secret == "true"
  tags: [ install, remove ]

- include_tasks: "ocp-lb.yml"
  when: ocp_prereq_lb == "true"
  tags: [ install, remove ]

#- include_tasks: "ocp-dns.yml"
#  when: ocp_prereq_dns == "true"
#  tags: [ install, remove ]

#- include_tasks: "ocp-http.yml"
#  when: ocp_prereq_http == "true"
#  tags: [ install, remove ]

#- include_tasks: "ocp-nfs.yml"
#  when: ocp_prereq_nfs == "true"
#  tags: [ install, remove ]

#- include_tasks: "ocp-dhcp.yml"
#  when: ocp_prereq_dhcp == "true"
#  tags: [ install, remove ]

#- include_tasks: "ocp-pxe.yml"
#  when: ocp_prereq_pxe == "true"
#  tags: [ install, remove ]

#- include_tasks: "ocp-artifacts.yml"
#  when: ocp_prereq_artifacts == "true"
#  tags: [ install, remove ]
