---

- name: Install OCP artifacts
  become: true
  tags: install
  block:

    - name: Create OpenShift artifacts directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '755'
      with_items:
        - "{{ ocp_install_path }}/artifacts/openshift-installer-{{ ocp_release }}"
        - "{{ ocp_install_path }}/artifacts/openshift-client-{{ ocp_release }}"
        - /var/www/html/images

    - name: Download VM image for install
      get_url:
        url: "{{ item }}"
        dest: /var/www/html/images/
      with_items:
        - "{{ ocp_mirror }}/dependencies/rhcos/4.{{ ocp_release.split('.')[1] | lower }}/latest/rhcos-{{ ocp_release }}-x86_64-metal.x86_64.raw.gz"
        - "{{ ocp_mirror }}/dependencies/rhcos/4.{{ ocp_release.split('.')[1] | lower }}/latest/rhcos-{{ ocp_release }}-x86_64-installer-kernel-x86_64"
        - "{{ ocp_mirror }}/dependencies/rhcos/4.{{ ocp_release.split('.')[1] | lower }}/latest/rhcos-{{ ocp_release }}-x86_64-installer-initramfs.x86_64.img"

    - name: Download Openshift installer
      unarchive:
        src: "{{ ocp_mirror }}/clients/ocp/{{ ocp_release }}/openshift-install-linux-{{ ocp_release }}.tar.gz"
        dest: "{{ ocp_install_path }}/artifacts/openshift-installer-{{ ocp_release }}/"
        remote_src: yes
        creates: "{{ ocp_install_path }}/artifacts/openshift-installer-{{ ocp_release }}/openshift-install"

    - name: Download Openshift client
      unarchive:
        src: "{{ ocp_mirror }}/clients/ocp/{{ ocp_release }}/openshift-client-linux-{{ ocp_release }}.tar.gz"
        dest: "{{ ocp_install_path }}/artifacts/openshift-client-{{ ocp_release }}/"
        remote_src: yes
        creates: "{{ ocp_install_path }}/artifacts/openshift-client-{{ ocp_release }}/oc"


    - name: Create a symbolic link for oc and installer
      ignore_errors: yes
      become: yes
      file:
        src: "{{ item.value }}"
        dest: "{{ item.key }}"
        state: link
        force: yes
      with_dict:
        "/usr/local/bin/oc": "{{ ocp_install_path }}/artifacts/openshift-client-{{ ocp_release }}/oc"
        "/usr/local/bin/openshift-install": "{{ ocp_install_path }}/artifacts/openshift-installer-{{ ocp_release }}/openshift-install"
    
    - name: Create installation directory
      file:
        path: "{{ ocp_install_path }}/install"
        state: directory

- name: Create ignition files
  when:
    - ocp_create_ignition == "true"
    - ocp_install_config_path != ""
  become: true
  tags: install
  block:
    
    - name: Create ignition files
      command: "{{ ocp_install_path }}/artifacts/openshift-installer-{{ ocp_release }}/openshift-install create ignition-configs"
      args:
        chdir: /var/www/html/ignition/

    - name: Recursively change ownership of ignition files
      file:
        path: /var/www/html/ignition/
        state: directory
        recurse: yes
        mode: 0555

- name: Remove OCP binaries
  become: true
  tags: remove
  block:

    - name: Remove directories
      ignore_errors: yes
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "/usr/local/bin/oc"
        - "/usr/local/bin/openshift-install"
        - "/var/www/html/images"
        - "/var/www/html/ignition"
        - "{{ ocp_install_path }}/install"
