---
# tasks file for ocp-prep
- name: Create install_config
  become: true
  tags: install
  block:
    - name: Install json package
      dnf:
        name: jq
        state: latest

    # go here to get your long lived access toekn https://cloud.redhat.com/openshift/token
    - name: Generate access token with offline token
      uri:
        url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
        method: POST
        body_format: form-urlencoded
        body:
        - [ grant_type, refresh_token ]
        - [ client_id, cloud-services ]
        - [ refresh_token, "{{ vault_token_long }}" ]
      register: access_tokens

    - name: Generate pull secret from access_token
      uri:
        url: https://api.openshift.com/api/accounts_mgmt/v1/access_token
        method: POST
        headers:
          Content-Type: application/yaml
          Authorization: "Bearer {{ access_tokens.json.access_token }}"
      register: pull_secret

    - debug:
        var: pull_secret

    - name: Create a directory for OCP install
      file:
        path: "{{ ocp_install_path }}"
        state: directory
        mode: '0755'

    - name: Generate SSH keys on Bastion
      openssh_keypair:
        path: /root/.ssh/id_rsa
      register: sshkey

    - name: Create ignition directory
      file:
        path: "/var/www/html/ignition/"
        state: directory
        mode: '0755'

    - name: Template a install_config file to ignition dir
      template:
        src: install-config.yaml.j2
        dest: "{{ ocp_install_config_path }}"

    - name: Template a install_config file backup
      template:
        src: install-config.yaml.j2
        dest: /var/www/html/install-config.yaml

- name: Remove install_config
  become: true
  tags: remove
  block:
    - name: Remove install_config
      file:
        path: "{{ ocp_install_config_path }}"
        state: absent