---

- name: Install PXE
  become: true
  tags: install
  block:

    - name: Install packages
      dnf:
        name: "{{ item }}"
        state: latest
      with_items:
        - tftp-server
        - dhcp-server
        - xinetd
        - syslinux

    - name: setup firewall
      firewalld:
        service: tftp
        permanent: yes
        state: enabled
        immediate: yes
        zone: public

#Put the boot iso in the web servers root directory manually when using tower
#    - name: "Copy over iso file to tftp server - {{ ansible_facts['nodename'] }}"
#      copy:
#        src: "{{ boot_iso }}"
#        dest: "/var/www/html/{{ boot_iso }}"

    - name: Mount boot iso read-only
      mount:
        path: "{{ mount_point }}"
        src: "/var/www/html/{{ boot_iso }}"
        fstype: iso9660
        opts: ro,noauto
        state: mounted

    - name: Copy over files for UEFI
      copy:
        remote_src: yes
        src: "{{ efi_dir }}/{{ item }}"
        dest: "{{ tftp_dir }}/uefi/{{ item }}"
      with_items: "{{ efifiles }}"

    - name: Copy over files for bios
      copy:
        remote_src: yes
        src: "{{ bios_dir }}/{{ item }}"
        dest: "{{ tftp_dir }}/pxelinux/{{ item }}"
      with_items: "{{ biosfiles }}"

    - name: Set up BIOS cfg boot files
      template:
        src: all-default.j2
        dest: "{{ tftp_dir }}/pxelinux/pxelinux.cfg/01-{{ item.macaddr | hwaddr('eui48') | lower }}"
        mode: '755'
      with_items:
        - "{{ nodes.masters }}"
        - "{{ nodes.workers }}"
        - "{{ nodes.bootstrap }}"

    - name: Template a file for custom grub menu onto tftp server
      template:
        src: grub.cfg-mac.j2
        dest: "{{ tftp_dir }}/uefi/grub.cfg-01-{{ item.macaddr | hwaddr('eui48') | lower }}"
        mode: '755'
      with_items:
        - "{{ nodes.masters }}"
        - "{{ nodes.workers }}"
        - "{{ nodes.bootstrap }}"

    - name: Start and ebable TFTP and xinetd service
      service:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      with_items:
        - tftp.service
        - xinetd.service

    - name: Unmount boot iso
      mount:
        path: "{{ mount_point }}"
        state: absent