---

- name: Install DNS
  become: true
  tags: install
  block:
    - name: Install needed packages
      yum:
        name:
          - bind
          - bind-utils
          - vim
          - bash-completion
          - python3-libselinux
          - firewalld
        state: present

    - name: Get Hostname
      shell: "hostname"
      register: dnshostname

    - name: Setting hostname as a fact
      set_fact:
        dnshostname: "{{ dnshostname.stdout }}"

    - name: Write out named file
      template:
        src: named.conf.j2
        dest: /etc/named.conf

    - copy:
        dest: "/usr/local/bin/set-dns-serial.sh"
        mode: '0555'
        content: |
          #!/bin/bash
          dnsserialfile=/usr/local/src/dnsserialXXXX.txt
          zonefile=/var/named/zonefile.db
          if [ -f zonefile ] ; then
            echo $[ $(grep serial ${zonefile}  | tr -d "\t"" ""\n"  | cut -d';' -f 1) + 1 ] | tee ${dnsserialfile}
          else
            if [ ! -f ${dnsserialfile} ] || [ ! -s ${dnsserialfile} ]; then
              echo $(date +%Y%m%d00) | tee ${dnsserialfile}
            else
              echo $[ $(< ${dnsserialfile}) + 1 ] | tee ${dnsserialfile}
            fi
          fi

    - name: Set zone serial number
      shell: "/usr/local/bin/set-dns-serial.sh"
      register: dymanicserialnumber

    - name: Setting serial number as a fact
      set_fact:
        serialnumber: "{{ dymanicserialnumber.stdout }}"

    - name: Write out "{{ dns.domain }}" zone file
      template:
        src: zonefile.j2
        dest: /var/named/zonefile.db

    - name: Write out reverse zone file
      template:
        src: reverse.j2
        dest: /var/named/reverse.db

    - name: Best effort SELinux repair - DNS
      shell: "restorecon -vR /var/named || true"

    - name: Starting services
      service:
        name: "{{ item }}"
        enabled: yes
        state: restarted
      with_items:
        - named

    - name: Set the local resolv.conf file
      template:
        src: resolv.conf.j2
        dest: /etc/resolv.conf

    - name: Configure Firewalld
      ignore_errors: yes
      firewalld:
        zone: public
        state: enabled
        permanent: yes
        immediate: yes
        port: 53/udp

- name: Remove DNS
  become: true
  tags: remove
  block:
    - name: Get Firewalld ZONE
      shell: "IFACE=$(nmcli con show '{{ srv_interface }}' | grep connection.interface-name | awk '{print $2}'); ZONE=$(firewall-cmd --list-all-zones | grep -B 3 $IFACE | head -n 1 | awk '{print $1}') ; echo $ZONE"
      register: firewalldzone

    - name: Configure Firewalld
      ignore_errors: yes
      firewalld:
        zone: "{{ firewalldzone.stdout }}"
        state: disabled
        permanent: yes
        port: "{{ item }}"
      with_items:
        - 53/udp

    - name: Reload Firewalld
      ignore_errors: yes
      shell: |
        firewall-cmd --reload

    - name: Remove packages
      yum:
        state: removed
        name: "{{ item }}"
      with_items:
        - bind
        - bind-utils
        - vim
        - bash-completion
        - libselinux-python

    - name: Remove  dirs
      ignore_errors: yes
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /var/named/zonefile.db
        - /var/named/reverse.db

    - name: Configure DNS forwarder as DNS server
      shell: "nmcli con mod '{{ srv_interface }}' ipv4.dns '{{ dns.forwarder2 | default('8.8.8.8') }} {{ dns.forwarder1 | default('8.8.4.4') }}' ; systemctl restart NetworkManager"
