---

- name: Install DNS
  become: true
  tags: install
  block:
    - name: Install needed packages
      yum:
        name:
          - bind
          - bind-utils
          - vim
          - bash-completion
          - python3-libselinux
          - firewalld
        state: present

    - name: Write out named file
      template:
        src: named.conf.j2
        dest: /etc/named.conf

    - name: Write out "{{ baseName }}.{{ baseDomain }}" zone file
      template:
        src: zonefile.j2
        dest: /var/named/zonefile.db

    - name: Write out reverse zone file
      template:
        src: reverse.j2
        dest: /var/named/reverse.db

    - name: Best effort SELinux repair - DNS
      shell: "restorecon -vR /var/named || true"

    - name: Starting services
      service:
        name: "{{ item }}"
        enabled: yes
        state: restarted
      with_items:
        - named

    - name: Set the local resolv.conf file
      template:
        src: resolv.conf.j2
        dest: /etc/resolv.conf

    - name: Configure Firewalld
      ignore_errors: yes
      firewalld:
        zone: public
        state: enabled
        permanent: yes
        immediate: yes
        port: 53/udp

- name: Remove DNS
  become: true
  tags: remove
  block:
    - name: Get Firewalld ZONE
      shell: "IFACE=$(nmcli con show '{{ srv_interface }}' | grep connection.interface-name | awk '{print $2}'); ZONE=$(firewall-cmd --list-all-zones | grep -B 3 $IFACE | head -n 1 | awk '{print $1}') ; echo $ZONE"
      register: firewalldzone

    - name: Configure Firewalld
      ignore_errors: yes
      firewalld:
        zone: "{{ firewalldzone.stdout }}"
        state: disabled
        permanent: yes
        port: "{{ item }}"
      with_items:
        - 53/udp

    - name: Reload Firewalld
      ignore_errors: yes
      shell: |
        firewall-cmd --reload

    - name: Remove packages
      yum:
        state: removed
        name: "{{ item }}"
      with_items:
        - bind
        - bind-utils
        - vim
        - bash-completion
        - libselinux-python

    - name: Remove  dirs
      ignore_errors: yes
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /var/named/zonefile.db
        - /var/named/reverse.db

    - name: Configure DNS forwarder as DNS server
      shell: "nmcli con mod '{{ srv_interface }}' ipv4.dns '{{ dns.forwarder2 | default('8.8.8.8') }} {{ dns.forwarder1 | default('8.8.4.4') }}' ; systemctl restart NetworkManager"
