---

- name: Install HTTP server
  become: true
  tags: install
  block:
    - name: Install needed packages
      dnf:
        name:
          - httpd
        state: latest

    - name: Configure Firewalld
      ignore_errors: yes
      firewalld:
        zone: public
        state: enabled
        permanent: yes
        service: "{{ item }}"
      with_items:
        - http
        - https

    - name: Starting services
      service:
        name: "{{ item }}"
        enabled: yes
        state: restarted
      with_items:
        - httpd
